{% set version = "6.8-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rms
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rms_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rms/rms_{{ version }}.tar.gz
  sha256: 9d38545749430763c242bae1181ce24a7f6f6b244e4c69348ab200b83925596a

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [ppc64le]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - r-base
    - r-cluster
    - r-colorspace
    - r-digest
    - r-ggplot2
    - r-hmisc >=5.1_0
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-knitr
    - r-mass
    - r-multcomp
    - r-nlme >=3.1_123
    - r-polspline
    - r-quantreg
    - r-rpart
    - r-sparsem
    - r-survival
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cluster
    - r-colorspace
    - r-digest
    - r-ggplot2
    - r-hmisc >=5.1_0
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-knitr
    - r-mass
    - r-multcomp
    - r-nlme >=3.1_123
    - r-polspline
    - r-quantreg
    - r-rpart
    - r-sparsem
    - r-survival

test:
  commands:
    - $R -e "library('rms')"           # [not win]
    - "\"%R%\" -e \"library('rms')\""  # [win]

about:
  home: https://hbiostat.org/R/rms/
  dev_url: https://github.com/harrelfe/rms
  license: GPL-2.0-or-later
  summary: "Regression modeling, testing, estimation, validation, graphics, prediction, and typesetting by storing enhanced model design attributes in the fit.  'rms' is a collection of functions that assist with and streamline modeling.  It also contains functions for binary and ordinal logistic regression models, ordinal
    models for continuous Y with a variety of distribution families, and the Buckley-James multiple regression model for right-censored responses, and implements penalized maximum likelihood estimation for logistic and ordinary linear models.  'rms' works with almost any regression model, but it was especially written to
    work with binary or ordinal regression models, Cox regression, accelerated failure time models, ordinary linear models,\tthe Buckley-James model, generalized least squares for serially or spatially correlated observations, generalized linear models, and quantile regression."
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
