{% set version = "6.0-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rms
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rms_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rms/rms_{{ version }}.tar.gz
  sha256: b82f5eb6b0e6aaedaed8b45f9b712809bf184adc860c60fd24d235ba19d66cfe

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-hmisc >=4.3_0
    - r-sparsem
    - r-ggplot2 >=2.2
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-lattice
    - r-multcomp
    - r-nlme >=3.1_123
    - r-polspline
    - r-quantreg
    - r-rpart
    - r-survival >=3.1_6
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-hmisc >=4.3_0
    - r-sparsem
    - r-ggplot2 >=2.2
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-lattice
    - r-multcomp
    - r-nlme >=3.1_123
    - r-polspline
    - r-quantreg
    - r-rpart
    - r-survival >=3.1_6

test:
  commands:
    - $R -e "library('rms')"           # [not win]
    - "\"%R%\" -e \"library('rms')\""  # [win]

about:
  home: http://biostat.mc.vanderbilt.edu/rms
  license: GPL-2
  summary: "Regression modeling, testing, estimation, validation, graphics, prediction, and typesetting by storing enhanced model design attributes in the fit.  'rms' is a collection of functions that assist with and streamline modeling.  It also contains functions for binary and ordinal logistic regression models, ordinal\
    \ models for continuous Y with a variety of distribution families, and the Buckley-James multiple regression model for right-censored responses, and implements penalized maximum likelihood estimation for logistic and ordinary linear models.  'rms' works with almost any regression model, but it was especially written\
    \ to work with binary or ordinal regression models, Cox regression, accelerated failure time models, ordinary linear models,\tthe Buckley-James model, generalized least squares for serially or spatially correlated observations, generalized linear models, and quantile regression."
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rms
# Version: 5.1-4
# Date: 2019-11-16
# Title: Regression Modeling Strategies
# Author: Frank E Harrell Jr <f.harrell@vanderbilt.edu>
# Maintainer: Frank E Harrell Jr <f.harrell@vanderbilt.edu>
# Depends: R (>= 3.5.0), Hmisc (>= 4.3-0), survival (>= 3.1-6), lattice, ggplot2 (>= 2.2), SparseM
# Imports: methods, quantreg, rpart, nlme (>= 3.1-123), polspline, multcomp, htmlTable (>= 1.11.0), htmltools
# Suggests: boot, tcltk, plotly (>= 4.5.6)
# Description: Regression modeling, testing, estimation, validation, graphics, prediction, and typesetting by storing enhanced model design attributes in the fit.  'rms' is a collection of functions that assist with and streamline modeling.  It also contains functions for binary and ordinal logistic regression models, ordinal models for continuous Y with a variety of distribution families, and the Buckley-James multiple regression model for right-censored responses, and implements penalized maximum likelihood estimation for logistic and ordinary linear models.  'rms' works with almost any regression model, but it was especially written to work with binary or ordinal regression models, Cox regression, accelerated failure time models, ordinary linear models,	the Buckley-James model, generalized least squares for serially or spatially correlated observations, generalized linear models, and quantile regression.
# License: GPL (>= 2)
# URL: http://biostat.mc.vanderbilt.edu/rms
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2019-11-17 02:38:23 UTC; harrelfe
# Repository: CRAN
# Date/Publication: 2019-11-17 14:30:03 UTC
