{% set version = '5.1-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rms
  version: {{ version|replace("-", "_") }}

source:
  fn: rms_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rms_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rms/rms_{{ version }}.tar.gz
  sha256: f1cfeef466ac436105756679353a3468027d97a600e3be755b819aef30ed9207

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-hmisc >=4.1_0
    - r-sparsem
    - r-ggplot2 >=2.2
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-lattice
    - r-multcomp
    - r-nlme >=3.1_123
    - r-polspline
    - r-quantreg
    - r-rpart
    - r-survival >=2.40_1
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-hmisc >=4.1_0
    - r-sparsem
    - r-ggplot2 >=2.2
    - r-htmltable >=1.11.0
    - r-htmltools
    - r-lattice
    - r-multcomp
    - r-nlme >=3.1_123
    - r-polspline
    - r-quantreg
    - r-rpart
    - r-survival >=2.40_1

test:
  commands:
    - $R -e "library('rms')"           # [not win]
    - "\"%R%\" -e \"library('rms')\""  # [win]

about:
  home: http://biostat.mc.vanderbilt.edu/rms
  license: GPL (>= 2)
  summary: "Regression modeling, testing, estimation, validation, graphics, prediction, and typesetting
    by storing enhanced model design attributes in the fit.  'rms' is a collection of
    functions that assist with and streamline modeling.  It also contains functions
    for binary and ordinal logistic regression models, ordinal models for continuous
    Y with a variety of distribution families, and the Buckley-James multiple regression
    model for right-censored responses, and implements penalized maximum likelihood
    estimation for logistic and ordinary linear models.  'rms' works with almost any
    regression model, but it was especially written to work with binary or ordinal regression
    models, Cox regression, accelerated failure time models, ordinary linear models,\tthe
    Buckley-James model, generalized least squares for serially or spatially correlated
    observations, generalized linear models, and quantile regression."
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
