travis:
  secure:
    BINSTAR_TOKEN: wB7i8aL8BnuZgpCWhsT23W8FU1bak8IsfHZGuwNJ3AtNpL9vWqILg87ZIQcakXse3I6Z76GvG97a2ipL12YS31gnZUyTMYmREJCNHDMR6QU817L5IHsXEPAGS8Sflo5hu6/QDp/WtJyIAH34gIjZC21WwZkgNw3mETmMHQudTU4fOCTHX6R31W6+YTJrJls524CxjIuZ22S9zMfFJFPC88AFuFxGcAba+gc60bH3QRnCUdOvA8mMpLuBQLK3Nr+F/Mp1X6Q/y1y1SEzl0BJwyQAQDpm1VVsoKAwJcEW4HuihxhFt68HzBoUtbQc+3U3JoRjCKJnqWG/YGtOPcgiBMN/eyJeez9cy/+Y+DNtO4VrP7odLW3JQyGyOOHREXOXHAgWDhHX0sMXIcBROI4NGds51iOsXwVbT7oCXTFtB5KRBd1uajmTmy4mtUSqfhGY4EOxIC6Yfzl3EuNCSMhKQ2NNQH8NOxkyztvD2QkZBLXB4rtEdPm3JoTH3WVCE+vhf74sr+ACMtffW2pyj748QKKc8G5/Z7qj/T5Ta3obYdFCxGtRpTvAP42MPa8y/GB+lKK5VB0zS9aQxTTr8jBW69elquc0blSFS5GEDKLwpw8cUpZzjKv+vqN5NCPPESCwPaM/GYpjDVisrIClGvf4NGCGjVnIRI361kjJtN/wSIDI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
