appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: KBVzf2skB6v+pQ5XVwNDXLoopP32L1RinbX2PLznaB/KKil+ENfQ+yxKPCFm2gdRW7OrLnEbtQl0jHhRJ5wC2cs/bG9cLKkMvknq1IBPNc54oP54d8H3kJMcyHpYx/EXExM5VD81rIYD9SRynj8fRVq8U2D6p42R8TR40j3Dz6m0pyx7JnQIQRtw5L0Gu0jTbmFJyJ5ZfY0i6sSbxBErB+yZxTz04vIjG0vh+lQNAdhXIyXzZkBSCspKR0SXbh0LL6opsKdQGBysmjCSwp0B4KbF1i9VWrWCRsrd96ttGT2y9vyxJki5s01oZ8jLDMNzNwWLr9CYZVwr/Iag+hcj0l6GYlgrtPdxsVvSK68G8m97XBvWFCfceWzjJKutdRe+Fr8QhFFZYIZ5sICZPtVNPUPr1RlvRqM2nDD87wZHYCfuQp3BoMWuyoBDZJ9xJ++KkTTSb+8/eLA2Y9/q7HxMfYq0YyK9bHcS1eJLj5/KjxQNF5X/wpMCjNDFW12pflIICgda8wc2VQEid6dlXhfyePpqb/kX7a7CdNsegGYJ7SPAPAyS4l1746WI2daQDcg79VIV9F8YCC28+jaMbnzRZ/jWPK2tg7Z91SFZ568Rsexv3vrUt7J1OPJ8XqGebW3gw+v4/9vcvp2espZcX9u4p3oVr1Xt9uAY4odg7PDgEok=}
